import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import '../styles/globals.scss'
import ContextProvider from '@/hooks/ContextProvider';
import QueryClinetProvider from '@/hooks/QueryClinetProvider';
import FeedbackProvider from '@/hooks/FeedbackProvider';

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Eqaim Project',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {

  return (
    <html lang="en">

      <body className={inter.className}>
        <QueryClinetProvider>
          <ContextProvider>
            <FeedbackProvider>
              {children}
            </FeedbackProvider>
          </ContextProvider>
        </QueryClinetProvider>
      </body>
    </html>
  )
}
